name: Laravel CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4"
          extensions: "mbstring, dom, fileinfo,mysql"
          coverage: none
      - name: Copy .env file
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install dependencies
        run: composer install -q --no-progress --prefer-dist --optimize-autoloader
      - name: Generate application key
        run: php artisan key:generate
      - name: Create database
        run: |
          mkdir -p database
          touch database/database.sqlite
      - name: Run migrations
        run: php artisan migrate
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
      - name: Execute tests
        run: php artisan test
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite

  deploy:
    needs: laravel-tests
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Verify deployment secrets
        run: |
          : "${{ secrets.SSH_HOST?Missing secret: SSH_HOST }}"
          : "${{ secrets.SSH_USER?Missing secret: SSH_USER }}"
          : "${{ secrets.SSH_PRIVATE_KEY?Missing secret: SSH_PRIVATE_KEY }}"
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/zaposlenje
            git pull origin main
            composer install --no-dev --optimize-autoloader
            php artisan migrate --force
            php artisan view:cache
            php artisan config:cache
            php artisan route:cache
